# Setup
title:               Abracadabra
tagline:             'ADA Datastory'
description:         'Welcome'
url:                 ''
baseurl:             'ada-story-epfl'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alexis Cogne
  url:               https://github.com/AlexisCogne
  email:             alexis.cogne@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
